#!/bin/python3

import configparser
import glob
import uuid

config = configparser.RawConfigParser()
entries = glob.glob('/usr/share/applications/*.desktop')

cats = {
    "Office" : "Office", 
    "Accessories": "Utility", 
    "Network": "Network", 
    "Graphics": "Graphics", 
    "Multimedia": "AudioVideo",
    "Settings": "Settings"
    }

desktopFiles = []
favorites = []

class DesktopItem:
    def __init__(self, name, types, command):
        self.name = name
        self.types = types
        self.command = command
        self.used = False

def cleanCommand(command):
    words = command.split()
    for word in words:
        if '%' in word:
            words.remove(word)
    return " ".join(words)

favorites.extend([
        DesktopItem("Terminal", None, "lxterminal"),
        DesktopItem("Web Browser", None, "firefox"),
        DesktopItem("Files", None, "pcmanfm")
        ])

for entry in entries:
    f = open(entry)
    newItem = ["None", "None", "None", "None"]

    for line in f:
        strings = line.split("=")
        if strings[0] == "Name" and newItem[0] == "None":
            newItem[0] = strings[1]
        if strings[0] == "Exec" and newItem[1] == "None":
            newItem[1] = strings[1]
        if strings[0] == "Categories":
            newItem[2] = strings[1]
        if strings[0] == "NoDisplay":
            newItem[3] = strings[1]

    if len(newItem) == 4 and newItem[3].strip() != "true":
        command = cleanCommand(newItem[1])
        desktopFiles.append(DesktopItem(newItem[0], newItem[2], command))

print("<openbox_pipe_menu>")
for fav in favorites:
    if fav.used == False:
        fav.used = True
        print("<item label=\"" + fav.name +"\"> <action name=\"Execute\"><command><![CDATA[" + fav.command + "]]></command></action></item>")

print("<separator label=\"Categories\"/>")
for cat in sorted(cats):
    print("<menu id=\"" + str(uuid.uuid1()) + "\" label=\"" + cat + "\">")
    for desktop in desktopFiles:
        if cats[cat] in desktop.types and desktop.used == False:
            desktop.used = True
            print("<item label=\"" + desktop.name +"\"> <action name=\"Execute\"><command><![CDATA[" + desktop.command + "]]></command></action></item>")
    print("</menu>")


print("<menu id=\"" + str(uuid.uuid1()) + "\" label=\"Other\">")
for desktop in desktopFiles:
    if desktop.used == False:
        desktop.used = True
        print("<item label=\"" + desktop.name +"\"> <action name=\"Execute\"><command><![CDATA[" + desktop.command + "]]></command></action></item>")
print("</menu>")
print("</openbox_pipe_menu>")
